default:
  interruptible: false
  image: 
    name: hashicorp/terraform:latest
    entrypoint: [""]
  
 
stages:
  - fmt
  - validate
  - init
  - plan
  - apply

.standart_rule:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


fmt_job:
  stage: fmt
  script:
    - terraform fmt -recursive
  extends:
    - .standart_rule

validate_job:
  stage: validate
  before_script :
    - terraform init
  script:
    - terraform validate  
  extends:
    - .standart_rule  


init_job:
  stage: init
  script:
    - terraform init  
  extends:
    - .standart_rule     

plan_job:
  stage: plan
  before_script :
    - terraform init
  script:
    - terraform plan -out=artifact/myplan    # need to create artifact
  artifacts:
    untracked: false
    when: on_success
    access: all
    expire_in: 10 days
    paths:
      - artifact/
  extends:
    - .standart_rule    


apply_job:
  stage: apply
  dependencies:
    - plan_job
  before_script :
    - terraform init  
  script:
    - terraform apply "artifact/myplan" 
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH